export const dicionario = {
  "aba": "Parte projetada de um chapéu que protege o rosto do sol ou da chuva. Pode ser também uma extensão de tecido em roupas.",
  "abacate": "Fruto do abacateiro, de casca verde e polpa macia, rica em gorduras boas. Muito usado em vitaminas, saladas e guacamole.",
  "abacaxi": "Fruta tropical de casca áspera e sabor agridoce, rica em vitamina C e usada em sucos, sobremesas e pratos salgados.",
  "amizade": "Relação duradoura de afeto, confiança e apoio mútuo entre pessoas. Considerada essencial para o bem-estar emocional.",
  "amor": "Sentimento profundo de carinho, afeição e ligação emocional, que pode ser romântico, fraternal, familiar ou universal.",
  "andar": "Ato de se locomover sobre os pés em posição ereta, podendo representar deslocamento físico ou progresso simbólico.",
  "alegria": "Estado emocional de felicidade e satisfação, frequentemente expresso com sorrisos, riso ou entusiasmo.",
  "alma": "Entidade imaterial considerada a essência do ser humano, relacionada à consciência, emoções e espiritualidade.",
  "água": "Líquido incolor e inodoro essencial à vida. Componente vital para todos os seres vivos, usada para hidratação e higiene.",
  "ar": "Mistura de gases que compõem a atmosfera terrestre, essencial para a respiração dos seres vivos.",
  "altura": "Distância vertical de um ponto em relação ao solo ou a outro ponto de referência. Pode indicar crescimento ou elevação.",
  "animal": "Ser vivo que se alimenta de outros organismos, sente, se move e reage a estímulos. Pode ser selvagem ou domesticado.",
  "ave": "Animal vertebrado com penas, asas e bico, geralmente capaz de voar. Exemplos incluem pássaros, águias e papagaios.",
  "aberto": "Que não está fechado ou lacrado. Pode se referir a portas, mentes, eventos ou sentimentos disponíveis.",
  "arte": "Forma de expressão humana que usa a criatividade para comunicar ideias e emoções por meio de sons, formas, imagens e movimentos.",
  "atitude": "Modo de agir ou reagir diante de uma situação. Reflete intenções, crenças ou disposições internas.",
  "ambiente": "Conjunto de condições físicas, sociais e culturais que cercam e influenciam os seres vivos ou um espaço específico.",
  "amarelo": "Cor entre o verde e o laranja no espectro da luz. Associada à luz solar, otimismo e atenção.",
  "azul": "Cor do céu em dias limpos e do mar em algumas regiões. Representa tranquilidade, confiança e serenidade.",
  "branco": "Cor que reflete todas as cores da luz. Simboliza pureza, paz, limpeza e simplicidade.",
  "beleza": "Qualidade de algo ou alguém que desperta admiração estética, harmonia e prazer visual ou emocional.",
  "bom": "Aquilo que possui qualidade positiva, atende a expectativas ou causa satisfação. Pode descrever pessoas, ações ou objetos.",
  "brisa": "Vento suave e agradável, normalmente associado a dias tranquilos e climas costeiros.",
  "bola": "Objeto redondo, usado em diversos esportes e brincadeiras. Pode simbolizar movimento, jogo e diversão.",
  "cabeça": "Parte superior do corpo humano onde estão o cérebro, os olhos, a boca e os ouvidos. Centro do pensamento e das expressões.",
  "cachorro": "Animal doméstico conhecido por sua lealdade, inteligência e amizade com os humanos. Também chamado de cão.",
  "calor": "Sensação provocada por temperaturas elevadas. Pode ser físico ou associado a emoções intensas.",
  "caminho": "Trajeto físico ou simbólico percorrido para se chegar a um destino. Pode representar jornada ou escolhas na vida.",
  "casa": "Construção destinada à moradia. Também representa o lar, onde se encontram conforto, segurança e afeto.",
  "céu": "Espaço visível acima da Terra, onde estão o sol, a lua, as estrelas e as nuvens. Simboliza o infinito ou espiritualidade.",
  "chuva": "Precipitação de gotas d'água que caem das nuvens. Importante para o ciclo da água e irrigação da natureza.",
  "cidade": "Área urbana densamente habitada, com infraestrutura, serviços e atividades econômicas e culturais.",
  "claro": "Que tem luz suficiente para ser bem visto. Também pode indicar algo evidente ou de fácil compreensão.",
  "comida": "Substância consumida para fornecer energia e nutrientes ao corpo. Pode variar conforme cultura e gosto.",
  "coração": "Órgão muscular que bombeia o sangue no corpo. Também símbolo de sentimentos como amor e emoção.",
  "cor": "Percepção visual resultante da luz refletida por objetos. Está presente em tudo ao nosso redor e influencia emoções.",
  "crescer": "Aumentar em tamanho, quantidade ou importância. Pode se referir ao corpo, à mente ou a experiências.",
  "criança": "Pessoa em fase inicial da vida. Representa inocência, aprendizado e desenvolvimento.",
  "cultura": "Conjunto de costumes, crenças, conhecimentos e expressões que caracterizam um grupo ou sociedade.",
  "dança": "Expressão artística por meio de movimentos corporais ritmados, geralmente acompanhados de música.",
  "dedo": "Parte fina e alongada que se projeta das mãos ou dos pés. Usado para tocar, segurar ou sentir.",
  "desenho": "Representação gráfica feita com traços em uma superfície. Pode ser artístico, técnico ou recreativo.",
  "dia": "Período de 24 horas que começa à meia-noite. Também se refere à parte clara de um ciclo solar.",
  "doce": "Alimento com sabor açucarado. Também pode descrever algo ou alguém delicado, afetuoso ou agradável.",
  "dormir": "Estado natural de repouso do corpo e da mente, essencial para o bem-estar e o funcionamento saudável.",
  "eco": "Repetição de um som refletido em superfícies. Também pode significar consequência ou ressonância de algo.",
  "energia": "Capacidade de realizar trabalho, movimento ou transformação. Pode ser física, elétrica, espiritual ou emocional.",
  "escola": "Instituição onde se ensina e se aprende. Ambiente de formação intelectual, social e pessoal.",
  "esperança": "Expectativa positiva de que algo bom acontecerá. Sentimento que motiva a perseverança diante das dificuldades.",
  "estudo": "Atividade de aprender, compreender ou se aprofundar em determinado conhecimento ou habilidade.",
  "família": "Grupo de pessoas unidas por laços sanguíneos, afetivos ou legais, que compartilham responsabilidades e convivência.",
  "felicidade": "Estado de satisfação plena e duradoura, associado ao bem-estar emocional, realização pessoal e relacionamentos positivos.",
  "festa": "Reunião de pessoas para celebrar algo com alegria, música, comida e convivência.",
  "fogo": "Reação de combustão que produz luz e calor. Símbolo de transformação, energia ou destruição.",
  "flor": "Estrutura colorida e perfumada de plantas que atrai polinizadores e simboliza beleza e renovação.",
  "frio": "Sensação térmica associada a temperaturas baixas. Pode provocar arrepios e necessidade de proteção.",
  "futuro": "Tempo que ainda não aconteceu. Carregado de possibilidades, incertezas e projeções.",
  "garoto": "Menino, criança do sexo masculino. Termo informal para designar jovens em idade infantil ou adolescente.",
  "gato": "Animal doméstico de hábitos independentes e comportamento carinhoso. Conhecido por sua agilidade e elegância.",
  "gelo": "Água no estado sólido, formada por congelamento. Usado para conservar alimentos ou refrescar bebidas.",
  "gente": "Conjunto de pessoas, usado de forma geral para se referir à humanidade ou a um grupo social.",
  "girar": "Executar movimento circular em torno de um ponto. Pode ser literal (como uma roda) ou metafórico (como mudanças).",
  "gosto": "Sensação percebida ao experimentar algo com o paladar. Também se refere a preferências ou opiniões.",
  "grama": "Planta rasteira com folhas finas, usada para cobrir o solo em jardins, parques e campos.",
  "guerra": "Conflito violento entre grupos organizados, geralmente nações, motivado por interesses políticos, econômicos ou religiosos.",
  "herói": "Pessoa admirada por seus feitos corajosos e altruístas, que age em benefício de outros, mesmo diante do perigo.",
  "história": "Narrativa de eventos passados, reais ou fictícios. Também é a disciplina que estuda o passado humano.",
  "homem": "Ser humano adulto do sexo masculino. Pode representar a humanidade em termos genéricos.",
  "hora": "Unidade de tempo equivalente a 60 minutos. Usada para medir e organizar o dia.",
  "ideia": "Representação mental de algo, uma concepção nova ou uma solução para determinado problema.",
  "ilha": "Porção de terra completamente cercada por água. Pode ser natural ou artificial.",
  "inverno": "Estação mais fria do ano, marcada por temperaturas baixas, dias curtos e menor incidência de luz solar.",
  "jardim": "Espaço cultivado com flores, plantas e árvores, usado para lazer, contemplação e embelezamento.",
  "jogo": "Atividade com regras definidas, que envolve competição ou cooperação com objetivo recreativo ou educativo.",
  "juiz": "Pessoa encarregada de julgar disputas com base na lei ou em regras estabelecidas.",
  "lago": "Grande porção de água doce cercada por terra. Pode ser natural ou artificial.",
  "lápis": "Instrumento para escrever ou desenhar, feito com mina de grafite envolta em madeira ou material plástico.",
  "lar": "Lugar onde alguém vive e sente acolhimento, segurança e afeto. Mais que casa, representa sentimento de pertencimento.",
  "leitura": "Ato de interpretar e compreender textos escritos. Ferramenta fundamental para o aprendizado e o pensamento crítico.",
  "luz": "Radiação visível que permite enxergar. Pode ser natural, como a do sol, ou artificial, como a elétrica.",
  "lua": "Satélite natural da Terra, visível principalmente à noite. Influencia as marés e inspira mitos e poesias.",
  "mãe": "Mulher que gera, adota ou cuida de um filho, exercendo papel fundamental na formação emocional e social.",
  "mão": "Extremidade do braço com dedos, usada para segurar, tocar e realizar diversas atividades.",
  "mar": "Grande massa de água salgada que cobre boa parte da Terra. Fonte de vida, alimento e transporte.",
  "massa": "Mistura de ingredientes usada como base de diversas receitas. Também pode significar grande quantidade ou grupo.",
  "medo": "Emoção natural diante de uma ameaça real ou imaginária. Serve como mecanismo de proteção.",
  "mel": "Substância doce produzida pelas abelhas a partir do néctar das flores. Tem valor nutricional e medicinal.",
  "mente": "Centro das atividades intelectuais e emocionais do ser humano. Relacionada à razão, memória, emoções e imaginação.",
  "mundo": "Planeta Terra ou o conjunto de tudo o que existe. Pode significar a realidade em que se vive.",
  "noite": "Período de escuridão entre o pôr e o nascer do sol. Associada ao descanso, ao silêncio e ao mistério.",
  "nuvem": "Formação de partículas de água ou gelo suspensas no céu. Pode indicar chuva ou servir de inspiração poética.",
  "olho": "Órgão da visão, sensível à luz e fundamental para a percepção do mundo ao redor.",
  "onda": "Movimento periódico que se propaga por um meio, como a água do mar. Também pode representar modas ou tendências.",
  "ouro": "Metal precioso de cor amarelada, muito valorizado por sua beleza e durabilidade. Usado em joias e finanças.",
  "paz": "Estado de harmonia, sem conflitos ou violências. Pode ser interior ou entre povos e nações.",
  "pai": "Homem que gera ou assume o papel de cuidar e educar um filho, oferecendo proteção, exemplo e apoio.",
  "palavra": "Unidade de linguagem que expressa um significado. É a base da comunicação escrita e falada.",
  "peixe": "Animal aquático que respira por brânquias. Pode viver em água doce ou salgada e é parte da alimentação humana.",
  "pensar": "Atividade mental de refletir, imaginar ou planejar. Essencial para a tomada de decisões e criação de ideias.",
  "perna": "Membro inferior do corpo humano, utilizado para locomoção e sustentação do corpo.",
};

  
  export const palavras = Object.keys(dicionario).sort();
  
  export function getRandomWord() {
    const idx = Math.floor(Math.random() * palavras.length);
    return palavras[idx];
  }