export const dicionario = {
    "aba": "Parte superior de um chapéu. Veja também: vestimenta.",
    "abacate": "Fruto do abacateiro, verde por fora e com polpa cremosa.",
    "abacaxi": "Fruta tropical com casca espinhosa e sabor ácido-doce.",
    "amizade": "Relação de afeto entre pessoas.",
    "amor": "Sentimento profundo de carinho.",
    "andar": "Deslocar-se de um lugar para outro com os pés.",
    "alegria": "Sentimento de prazer e felicidade.",
    "alma": "Parte imaterial do ser humano.",
    "água": "Substância líquida essencial à vida.",
    "ar": "Mistura gasosa que envolve a Terra.",
    "altura": "Medida da distância vertical.",
    "animal": "Ser vivo que não é planta ou fungo.",
    "ave": "Animal com penas, bico e asas.",
    "aberto": "Que não está fechado.",
    "arte": "Expressão criativa por meio de formas e sons.",
    "atitude": "Comportamento diante de algo.",
    "ambiente": "Espaço ao redor de algo ou alguém.",
    "amarelo": "Cor entre o verde e o laranja.",
    "azul": "Cor do céu em dias claros.",
    "branco": "Cor clara, da neve.",
    "beleza": "Qualidade do que é belo.",
    "bom": "De qualidade positiva.",
    "brisa": "Vento leve e agradável.",
    "bola": "Objeto redondo usado em jogos.",
    "cabeça": "Parte superior do corpo.",
    "cachorro": "Animal doméstico fiel e companheiro.",
    "calor": "Sensação térmica elevada.",
    "caminho": "Direção ou rota a seguir.",
    "casa": "Construção onde alguém mora.",
    "céu": "Espaço visível acima da Terra.",
    "chuva": "Precipitação de gotas d'água.",
    "cidade": "Área urbana com muitos habitantes.",
    "claro": "Que tem luz ou cor suave.",
    "comida": "Substância ingerida como alimento.",
    "coração": "Órgão vital que bombeia sangue.",
    "cor": "Impressão visual causada pela luz.",
    "crescer": "Aumentar de tamanho ou importância.",
    "criança": "Pessoa de pouca idade.",
    "cultura": "Conjunto de hábitos e conhecimentos.",
    "dança": "Movimento ritmado do corpo com música.",
    "dedo": "Extremidade dos pés ou mãos.",
    "desenho": "Representação gráfica com linhas.",
    "dia": "Período de 24 horas.",
    "doce": "Com sabor de açúcar.",
    "dormir": "Entrar em estado de repouso.",
    "eco": "Repetição do som refletido.",
    "energia": "Capacidade de realizar trabalho.",
    "escola": "Instituição para ensino.",
    "esperança": "Sentimento de que algo bom vai acontecer.",
    "estudo": "Ato de aprender ou pesquisar algo.",
    "família": "Grupo de pessoas com laços de sangue ou afeto.",
    "felicidade": "Estado de contentamento intenso.",
    "festa": "Celebração com alegria.",
    "fogo": "Combustão que libera calor e luz.",
    "flor": "Parte colorida de uma planta.",
    "frio": "Temperatura baixa.",
    "futuro": "Tempo que ainda virá.",
    "garoto": "Menino, criança do sexo masculino.",
    "gato": "Animal doméstico felino.",
    "gelo": "Água congelada.",
    "gente": "Grupo de pessoas.",
    "girar": "Mover-se em círculos.",
    "gosto": "Sensação do paladar.",
    "grama": "Relva de pequenos caules.",
    "guerra": "Conflito armado entre grupos.",
    "herói": "Pessoa admirada por coragem.",
    "história": "Conjunto de eventos do passado.",
    "homem": "Ser humano adulto do sexo masculino.",
    "hora": "Unidade de tempo com 60 minutos.",
    "ideia": "Pensamento ou plano.",
    "ilha": "Terra cercada por água.",
    "inverno": "Estação mais fria do ano.",
    "jardim": "Área com plantas e flores.",
    "jogo": "Atividade com regras e objetivo.",
    "juiz": "Pessoa que decide sobre leis.",
    "lago": "Grande porção de água cercada por terra.",
    "lápis": "Objeto usado para escrever ou desenhar.",
    "lar": "Lugar onde se vive com afeto.",
    "leitura": "Ato de interpretar palavras escritas.",
    "luz": "Radiação que torna possível ver.",
    "lua": "Satélite natural da Terra.",
    "mãe": "Mulher que gerou ou cuida de um filho.",
    "mão": "Extremidade do braço com dedos.",
    "mar": "Grande corpo de água salgada.",
    "massa": "Mistura de ingredientes.",
    "medo": "Sensação de perigo.",
    "mel": "Substância doce feita por abelhas.",
    "mente": "Capacidade de pensar e sentir.",
    "mundo": "Planeta Terra ou totalidade da existência.",
    "noite": "Período entre o pôr e o nascer do sol.",
    "nuvem": "Massa visível de gotículas no céu.",
    "olho": "Órgão da visão.",
    "onda": "Movimento da superfície da água.",
    "ouro": "Metal precioso e brilhante.",
    "paz": "Ausência de conflito.",
    "pai": "Homem que gerou ou cuida de um filho.",
    "palavra": "Unidade de linguagem com significado.",
    "peixe": "Animal aquático com barbatanas.",
    "pensar": "Processar ideias na mente.",
    "perna": "Membro inferior do corpo.",
  };
  
  export const palavras = Object.keys(dicionario).sort();
  
  export function getRandomWord() {
    const idx = Math.floor(Math.random() * palavras.length);
    return palavras[idx];
  }